#!/bin/bash

# Create individual SQL files for each database. These files
# are imported automatically during an initial provision if
# the databases exist per the import-sql.sh process.
current_time=$(date "+%Y.%m.%d-%H.%M.%S")
mysql --user="root" --password="{%= bonzai.env.BONZAI_DB_ROOT %}" -e 'show databases' | \
grep -v -F "information_schema" | \
grep -v -F "performance_schema" | \
grep -v -F "mysql" | \
grep -v -F "test" | \
grep -v -F "Database" | \
while read dbname; do mysqldump --user="root" --password="{%= bonzai.env.BONZAI_DB_ROOT %}" "$dbname" > /var/www/backups/databases/"$dbname"-"$current_time".sql && echo "Database $dbname backed up..."; done