vagrantfile:
    vm:
        provider:
            local:
                chosen_virtualizer: {%= current.user.vagrant.provider %}
                machines:
                    vflm_21tvv5gqiefp:
                        id: {%= pkg.name %}
                        hostname: vm.{%= pkg.name %}.local
                        network:
                            private_network: {%= current.user.vagrant.ip %}
                        memory: '{%= current.user.vagrant.memory %}'
                        cpus: '{%= current.user.vagrant.cpus %}'
    ssh:
        private_key_path: '{%= bonzai.env.BONZAI_CURRENT_USER_RSA %}'
        forward_agent: true