vagrantfile:
    vm:
        provider:
            local:
                chosen_virtualizer: {%= current.user.vagrant.provider %}
                machines:
                    machine1:
                        id: {%= pkg.name %}
                        hostname: {%= pkg.name %}.puphpet
                        network:
                            private_network: {%= current.user.vagrant.ip %}
                            forwarded_port:
                                port1:
                                    host: '6762'
                                    guest: '22'
                        memory: '{%= current.user.vagrant.memory %}'
                        cpus: '{%= current.user.vagrant.cpus %}'
    ssh:
        private_key_path: '{%= bonzai.env.BONZAI_CURRENT_USER_RSA %}'
        forward_agent: true