ip: 192.168.10.10
memory: 2048
cpus: 2
provider: virtualbox
authorize: ~/.ssh/id_rsa.pub
keys:
    - ~/.ssh/id_rsa
folders:
    -
        map: 'D:\Projets\{%= pkg.name %}'
        to: /home/vagrant/code
sites:
    -
        map: {%= pkg.name %}.test
        to: /home/vagrant/code/{%= app.webRoot %}
databases:
    - {%= pkg.name %}
name: {%= pkg.name %}
hostname: {%= pkg.name %}.homestead
